### ISSUE TITLE
Generating go server causes error with parsing RAML

### ISSUE THREAD

**Issue by marcusljx** [Jumpscale/go-raml#182]
When I run the example command
```
go-raml server -l go --dir ./server --ramlfile _api/api.raml --import-path ./_api
```
I get this error output immediately. There's no other debug information.
```
time="2016-11-18T16:10:38+08:00" level=info msg="Generating a go server"
line 25: cannot unmarshal !!map into string
source:  mapping
line 82: cannot unmarshal !!map into string
source:  mapping
line 154: cannot unmarshal !!map into string
source:  mapping
line 217: cannot unmarshal !!map into string
source:  mapping
line 241: cannot unmarshal !!map into string
source:  mapping
line 261: cannot unmarshal !!map into string
source:  mapping
line 345: cannot unmarshal !!map into string
source:  mapping
line 368: cannot unmarshal !!map into string
source:  mapping
line 440: cannot unmarshal !!map into string
source:  mapping
line 460: cannot unmarshal !!map into string
source:  mapping
line 591: cannot unmarshal !!map into string
source:  mapping
time="2016-11-18T16:10:38+08:00" level=error msg="Error parsing RAML:\n  line 25: string value cannot be of type mapping, must be string\n  line 82: string value cannot be of type mapping, must be string\n  line 154: string value cannot be of type mapping, must be string\n  line 217: string value cannot be of type mapping, must be string\n  line 241: string value cannot be of type mapping, must be string\n  line 261: string value cannot be of type mapping, must be string\n  line 345: string value cannot be of type mapping, must be string\n  line 368: string value cannot be of type mapping, must be string\n  line 440: string value cannot be of type mapping, must be string\n  line 460: string value cannot be of type mapping, must be string\n  line 591: string value cannot be of type mapping, must be string\n"
```

This is weird because my RAML file does not have more than 190 lines. It is a relatively simple API. The only thing I can recognise is that `line 25` (where the error first occurs) is `type: !include schemas/search.json`.

I'm running it on a RAML1.0 file validated through api-workbench. The JSON schema files have also been validated.

Has anyone encountered this error before and know if I am doing anything wrong?

**Comment by iwanbk** [comment]
Hi, can you please provide your .raml files?

**Comment by marcusljx** [comment]
Hi there, I figured out the problem.

The issue is that `go-raml` currently still parses `schema: !include ...` which is for compatibility with RAML0.8 only. In RAML1.0 this is actually deprecated and the node `type` is supposed to be used instead.

As quoted from https://github.com/raml-org/raml-spec/blob/7c709f7332fc031c36fbca050845aa3963edc3b8/versions/raml-10/raml-10.md#using-xml-and-json-schema :

> The nodes "schemas" and "types", as well as "schema" and "type", are mutually exclusive and synonymous for compatibility with RAML 0.8. API definitions should use "types" and "type", as "schemas" and "schema" are deprecated and might be removed in a future RAML version.

As a workaround, I suggest to RAML1.0 users to change their `type` nodes back to `schema` just for the code generation stage. Ultimately I believe this is a bug in `go-raml` and should be fixed.

**Comment by iwanbk** [comment]
@marcusljx 
thanks for this issue.

I've checked it and from my test it works.
This is .raml file i use https://gist.github.com/iwanbk/014482c0acf6dd6cf1e5baec1a9a3b14, let me know if you have different case.

On the other hand, i can see that JSON handling can be improved, it should happen soon.

**Comment by iwanbk** [comment]
@marcusljx 

I can finally reproduce it

**Comment by iwanbk** [comment]
@marcusljx 

something like this?

```
/person:
  get:
    responses:
      200:
        body:
          application/json:
            type: !include person.json
```

**Comment by iwanbk** [comment]
@marcusljx 

Because i don't know your user case, can you please try `json-improvement` branch.

It supports these:
- include JSON both in `types` and  in `application/json` of body
- inline JSON in `application/json` of body

inline JSON in `types` still not supported.

**Comment by iwanbk** [comment]
@marcusljx 

```
The issue is that go-raml currently still parses schema: !include ... which is for compatibility with RAML0.8 only
```
go-raml code generator actually only supports `type`, the problem was in the JSON support.
Fixed at #187

**Comment by iwanbk** [comment]
```
Fixed at #187
```
Please reopen if you still have issue

**Comment by pruflyos** [comment]
`cannot unmarshal !!map into string`

This issue still appears when you use the `mediaType: application/json` property on the **top level** of the RAML file to **specify a default media type** and **omit** it in the requests and responses.

Here's the existing [example fixture](https://github.com/Jumpscale/go-raml/blob/master/codegen/fixtures/raml-examples/defining-examples/organisation-api.raml) adjusted so it breaks:
```yaml
#%RAML 1.0
title: API with Examples
mediaType: application/json

types:
  User:
    type: object
    properties:
      name: string
      lastname: string
    example:
      name: Bob
      lastname: Marley
  Org:
    type: object
    properties:
      name: string
      address?: string
      value? : string
/organisation:
  post:
    headers:
      UserID:
        description: the identifier for the user that posts a new organisation
        type: string
        example: SWED-123 # single scalar example
    body:
      type: Org
      example: # single request body example
        value: # needs to be declared since type contains 'value' property
          name: Doe Enterprise
          value: Silver
  get:
    description: Returns an organisation entity.
    responses:
      201:
        body:
          type: Org
          example:
            softwareCorp:
              value: # validate against the available facets for the map value of an example
                name: Software Corp
                address: 35 Central Street
                value: Gold # validate against instance of the `value` property
```

```
Generating a go server                       
line 29: cannot unmarshal !!map into string
source:  mapping
line 39: cannot unmarshal !!map into string
source:  mapping
ERROR Error parsing RAML:
  line 29: string value cannot be of type mapping, must be string
  line 39: string value cannot be of type mapping, must be string
```
